relativeURLs = true
languageCode = "en-us"
title = "Mostly Rambling"
theme = "etch"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
disableKinds = ["taxonomy", "term"]

[params]
  description = "Just a bunch of rambling about almost anything."
  dark = "auto"
  highlight = true

[minify]
  minifyOutput = true

[menu]

  [[menu.main]]
    identifier = "all posts"
    title = "all posts"
    name = "all posts"
    url = "/posts"
    weight = 1

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true