relativeURLs = true
languageCode = "en-us"
title = "Mostly Rambling"
theme = "basicwebtheme"

[params]
  headertext = "Mostly Rambling"
  bigtitle = true

[minify]
  minifyOutput = true

[menu]

  [[menu.main]]
    title = "Home"
    name = "The homepage"
    url = "/"
    weight = 1

  [[menu.main]]
    title = "Posts"
    name = "All posts"
    url = "/posts"
    weight = 2
