languageCode = "en-us"
title = "Mostly Rambling"
theme = "etch"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
disableKinds = ["taxonomy", "term"]

[params]
  description = "Just a bunch of rambling about almost anything."
  dark = "auto"
  highlight = true

[minify]
  minifyOutput = true

[menu]

  [[menu.main]]
    identifier = "posts"
    title = "posts"
    name = "posts"
    url = "/"
    weight = 10

[permalinks]
  posts = "/:filename/"
  
[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true